# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1d01ca4b56e0d376f791c141f32055964b7c67a74c8f72052a7998cf79bc68a2d0ada62fced3d2260c6744a374070dbc2ee89c1a18b4be000aa5b36d106c45f
  amazon_key: <%=ENV["AMAZON_KEY"]%>
  amazon_secret: <%=ENV["AMAZON_SECRET"]%>
  clarifai_client_id: <%=ENV["CLARIFAI_CLIENT_ID"]%>
  clarifai_client_secret: <%=ENV["CLARIFAI_CLIENT_SECRET"]%>
  portfolio_s3_bucket: <%=ENV["PORTFOLIO_S3_BUCKET"]%>

test:
  secret_key_base: 50b73616b7d638442456ce252e1281fc47cae2f0b1ab7664d8af84999c7eed8e78d4e15ee2c6051dfbb7fd14d6ab32f5d2b55398b6210530356f17fa68891ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  amazon_key: <%=ENV["AMAZON_KEY"]%>
  amazon_secret: <%=ENV["AMAZON_SECRET"]%>
  clarifai_client_id: <%=ENV["CLARIFAI_CLIENT_ID"]%>
  clarifai_client_secret: <%=ENV["CLARIFAI_CLIENT_SECRET"]%>
  portfolio_s3_bucket: <%=ENV["PORTFOLIO_S3_BUCKET"]%>
